name: CI workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v6

       - name: setup nodejs
         uses: actions/setup-node@v6
         with:
           node-version: 22
           cache: "npm"

       - name: install dep
         run: npm ci

       - name: run linter
         run: npm run lint


   test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: install dependencies
        run: npm ci
      - name: test code
        run: npm run test

   build:
     needs: [lint, test]
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4

       - name: setup node.js
         uses: actions/setup-node@v4
         with:
           node-version: 22
           cache: 'npm'

       - run: npm run build
